### ISSUE TITLE
not running on GPU

### ISSUE THREAD

**Issue by geocine** [pykeio/diffusers#10]
When I am running script from https://github.com/pykeio/diffusers/blob/main/examples/stable-diffusion.rs . Its using up my CPU and system Memory. I don't see the GPU being utilized

![image](https://user-images.githubusercontent.com/507464/210163998-91cf9678-c638-409e-9a56-0ec26558c433.png)

I have the following setup:

May `Cargo.toml` looks like this

```toml
[dependencies]
pyke-diffusers = "0.1"
```
Output of `nvidia-smi`

```sh
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.56       Driver Version: 527.56       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:0A:00.0  On |                  N/A |
|  0%   50C    P5    38W / 220W |    988MiB /  8192MiB |     11%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

Output of `nvcc -v`

```sh
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:28:54_Pacific_Standard_Time_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0
```

From `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include\cudnn_version.h` version is `8.6.0`

```cpp
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 0
```

![image](https://user-images.githubusercontent.com/507464/210164130-7db42f73-055a-4b63-ab9a-f185976fa79b.png)

I have successfully run CUDA workloads on this machine outside of this library

**Comment by sudo-carson** [comment]
Make sure you've enabled the `ort-cuda` Cargo feature. You may have to `cargo clean` and rebuild. Sorry, I should've been more clear in the docs.

**Comment by geocine** [comment]
Thanks, you did mention in the docs to use `ort-cuda` . I forgot to uncomment when I was trying to make `fp16` work on the other issue I opened. All good now
