### ISSUE TITLE
Example failed without any reason

### ISSUE THREAD

**Issue by oovm** [pykeio/diffusers#18]
I tried the following commands, but no `result.png` was generated, and no error message was reported.

```sh
cargo run --example stable-diffusion --features ort-cuda
```

```rust
RUST_BACKTRACE=FULL cargo run --example stable-diffusion --features ort-cuda
   Compiling pyke-diffusers v0.2.0 (D:\Python\diffusers)
    Finished dev [unoptimized + debuginfo] target(s) in 1.84s
     Running `target\debug\examples\stable-diffusion.exe`
error: process didn't exit successfully: `target\debug\examples\stable-diffusion.exe` (exit code: 0xc000007b)
```

**Comment by sudo-carson** [comment]
Did you copy the DLLs from `target/debug` to `target/debug/examples`?

https://github.com/pykeio/diffusers#onnx-runtime-binaries

**Comment by oovm** [comment]
Copying `onnxruntime*.dll` works.

Can an environment variable be specified to tell the path of the dynamic library?

I refer: https://github.com/pykeio/ort#shared-library-hell

I unpacked `onnxruntime-win-x64-gpu-1.14.0` to `D:\onnxruntime`, then set the environment variable:

```sh
ORT_STRATEGY='D:\onnxruntime\lib'
```

But it doesn't work

**Comment by sudo-carson** [comment]
> Can an environment variable be specified to tell the path of the dynamic library?

Not on Windows, see https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-unpackaged-apps

While you can add the libraries to `PATH`, on some systems it will find the `onnxruntime.dll` in System32, which on my machine is on ONNX Runtime v1.13, when this library expects 1.14, so you'd get an error.

**Comment by oovm** [comment]
When I distribute my executable, do I need to package the dynamic library of `onnxruntime`? 

Is there a way to use pure static linking?

**Comment by sudo-carson** [comment]
> When I distribute my executable, do I need to package the dynamic library of `onnxruntime`?

Yes

> Is there a chance to use pure static linking?

Yes and no, static linking ONNX Runtime isn't well supported by Microsoft. You could give it a try, compile ONNX Runtime from source, and use `ort`'s system strategy to link to the static libraries. I am also not sure if the CUDA provider can be static linked or not.

**Comment by sudo-carson** [comment]
Hey @oovm, I updated `ort` to be able to load ONNX Runtime DLLs from an environment variable here: https://github.com/pykeio/ort/commit/930edb6c17e20570d4ff124e6f6b0e961870d62c

It can be configured with `ORT_DYLIB_PATH=C:\path\to\onnxruntime.dll` as long as the feature `load-dynamic` is enabled for `ort`.

Until I publish a new pyke-diffusers/ort release (might be a few days), feel free to fork diffusers and modify its `Cargo.toml` to use `ort` as a Git dependency:
```toml
ort = { git = "https://github.com/pykeio/ort.git", default-features = false, features = [ "load-dynamic" ] }
```

**Comment by oovm** [comment]
`load-dynamic` features confirmed.

It is very interesting that even if `onnxruntime_providers_cuda.dll` does not exist,  `ExecutionProvider::cuda()` is still available.

```rust 
    println!("{}", env!("ORT_STRATEGY"));      // system
    println!("{}", env!("ORT_LIB_LOCATION"));  // D:\onnxruntime\lib
    println!("{}", env!("ORT_DYLIB_PATH"));    // D:\onnxruntime\lib\onnxruntime.dll
    println!("{}", ExecutionProvider::cuda().is_available())  // true
```

I'm not sure if it actually called the library in `D:\onnxruntime\lib`
