### ISSUE TITLE
More pipelines

### ISSUE THREAD

**Issue by decahedron1** [pykeio/diffusers#2]
- [x] Stable Diffusion text-to-image
- [x] "Safe" Stable Diffusion
- [ ] Stable Diffusion image-to-image
- [ ] Stable Diffusion inpainting
- [ ] Stable Diffusion v2 upscaling
- [ ] Stable Diffusion v2 image variation
- [ ] Versatile Diffusion
- [ ] AudioLDM

# Pipelines to explore
May or may not be implemented depending on complexity.

- [ ] [Stable Diffusion outpainting](https://github.com/lkwq007/stablediffusion-infinity)
- [ ] Paint By Example
- [ ] Latent Diffusion
- [ ] Latent Diffusion super-resolution
- [ ] Unconditional Latent Diffusion
- [ ] Cycle Diffusion
- [ ] Dance Diffusion
- [ ] DeepFloyd IF
- [ ] [ControlNet](https://github.com/lllyasviel/ControlNet)

**Comment by be5invis** [comment]
One feature used frequently in recent AI painting community: [ControlNet](https://github.com/lllyasviel/ControlNet)
