### ISSUE TITLE
Text encoder changed on every convert

### ISSUE THREAD

**Issue by oovm** [pykeio/diffusers#24]
Continue the discussion on this topic: https://github.com/pykeio/diffusers/issues/19#issuecomment-1465224551

I've used the same settings to convert, but each result is different.

```sh
# anything-v2.1-fp16
rm -rf ./anything-v2.1-fp16
wget https://huggingface.co/swl-models/anything-v2.1/resolve/main/anything-V2.1-pruned-fp16.safetensors -ci
python scripts/sd2pyke.py ./anything-V2.1-pruned-fp16.safetensors ./anything-v2.1-fp16 --fp16 -C v1-inference.yaml
# anything-v3.0-fp16
rm -rf ./anything-v3.0-fp16
wget https://huggingface.co/Linaqruf/anything-v3.0/resolve/main/anything-v3.0-pruned-fp16.safetensors -ci
python scripts/sd2pyke.py ./anything-v3.0-pruned-fp16.safetensors ./anything-v3.0-fp16 --fp16 -C v1-inference.yaml
# anything-v4.0-fp16
rm -rf ./anything-v4.0-fp16
wget https://huggingface.co/andite/anything-v4.0/resolve/main/anything-v4.0-pruned-fp16.safetensors -ci
python scripts/sd2pyke.py ./anything-v4.0-pruned-fp16.safetensors ./anything-v4.0-fp16 --fp16 -C v1-inference.yaml
# anything-v4.5-fp16
rm -rf ./anything-v4.5-fp16
wget https://huggingface.co/andite/anything-v4.0/resolve/main/anything-v4.5-pruned-fp16.ckpt -ci
python scripts/sd2pyke.py ./anything-v4.5-pruned-fp16.ckpt ./anything-v4.5-fp16 --fp16 -C v1-inference.yaml
```

Did not add `--simplify-small-models`, all stable diffusion v1.4/v1.5 models.

- [anything-v2.1-fp16/diffusers.json](https://huggingface.co/oovm/Anything/blob/ab7993c1a502ea6317ce9d5cfeac9408340be7f9/anything-v2.1-fp16/diffusers.json#L33)
- [anything-v3.0-fp16/diffusers.json](https://huggingface.co/oovm/Anything/blob/ab7993c1a502ea6317ce9d5cfeac9408340be7f9/anything-v3.0-fp16/diffusers.json#L33)
- [anything-v4.0-fp16/diffusers.json](https://huggingface.co/oovm/Anything/blob/ab7993c1a502ea6317ce9d5cfeac9408340be7f9/anything-v4.0-fp16/diffusers.json#L33)
- [anything-v4.5-fp16/diffusers.json](https://huggingface.co/oovm/Anything/blob/ab7993c1a502ea6317ce9d5cfeac9408340be7f9/anything-v4.5-fp16/diffusers.json#L33)

which returns

```
f4ecc275e2e11ff894a4fc4cf9842be7
f4ecc275461c2d2f97f0014f04f91871
f4ecc2758656992cf0d63b36c2c3d429
f4ecc27546d38ab39278e2a9deb5a860
```

The file pointer of lfs also generates four different, waste extra 200m bandwidth and space per model.

Might need an option to directly copy/download the original encoder

**Comment by sudo-carson** [comment]
`sd2pyke` always converts the same text encoder: [`openai/clip-vit-large-patch14`](https://huggingface.co/openai/clip-vit-large-patch14), see [here](https://github.com/huggingface/diffusers/blob/bbab8553224d12f7fd58b0e65b0daf899769ef0b/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L729-L742), but it seems like the Stable Diffusion checkpoint can contain some `cond_stage_model.transformer` tensors which modify the weights of the text encoder and can this change the output hash.

In my case, at least AOM2_sfw does contain these keys, which explains why the hashes are different. The text encoder's weights are genuinely different between the models. This is not a bug.

**Comment by sudo-carson** [comment]
Additionally my text encoder hash for AOM2_sfw (converted with hf2pyke) and AOM2_nsfw (converted with sd2pyke) are both identical: `f4ecc275461c2d2f97f0014f04f91871`, so the conversion scripts are not nondeterministic.
