### ISSUE TITLE
window 10 pycharm install imohash fail

### ISSUE THREAD

**Issue by ZTMIDGO** [pykeio/diffusers#26]
Unable to install imohash>=1.0.4

window 10 21H2
python：3.10
PyCharm 2022.3.3 (Community Edition)

---------------------------------------------------------------------------------------------------

PS D:\python\diffusers> pip install imohash
Collecting imohash
  Using cached imohash-1.0.4-py2.py3-none-any.whl (8.4 kB)
Collecting varint>=1.0.2
  Using cached varint-1.0.2.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Collecting mmh3>=2.5.1
  Using cached mmh3-3.0.0.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mmh3, varint
  Building wheel for mmh3 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'mmh3' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmh3
  Running setup.py clean for mmh3
  Building wheel for varint (setup.py) ... done
  Created wheel for varint: filename=varint-1.0.2-py3-none-any.whl size=1962 sha256=db97263262e91ced32abe24043cd50febdcc187e5b079e0fe8df4a60a032d059
  Stored in directory: c:\users\ztmidgo\appdata\local\pip\cache\wheels\39\48\5e\33919c52a2a695a512ca394a5308dd12626a40bbcd288de814
Successfully built varint
Failed to build mmh3
Installing collected packages: varint, mmh3, imohash
  Running setup.py install for mmh3 ... error
  error: subprocess-exited-with-error

  × Running setup.py install for mmh3 did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running install
      C:\software\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'mmh3' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> mmh3

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by sudo-carson** [comment]
Install Visual Studio Build Tools: https://visualstudio.microsoft.com/visual-cpp-build-tools/
