### ISSUE TITLE
error bulling on android 

### ISSUE THREAD

**Issue by Fcucgvhhhvjv** [pykeio/diffusers#31]
error in termux 

error: failed to run custom build command for `ort v1.14.6 (https://github.com/pykeio/ort?rev=5d064ceb675104c6f7e72770b3e48d43fdc450b2#5d064ceb)`                                                                                   Caused by:                                                                    process didn't exit successfully: `/data/data/com.termux/files/home/diffusers/target/release/build/ort-cf34fc101a99e5ca/build-script-build` (exit status: 101)                                                                      --- stdout
  [ort] strategy: "unknown"                                                   cargo:rerun-if-env-changed=ORT_STRATEGY                                                                                                                 --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Unsupported OS: android"', /data/data/com.termux/files/home/.cargo/git/checkouts/ort-675c4f2a84c4db27/5d064ce/build.rs:183:87                              note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                         warning: build failed, waiting for other jobs to finish...

**Comment by decahedron1** [comment]
You need to build ONNX Runtime from source.
https://github.com/pykeio/ort#how-to-get-binaries

**Comment by decahedron1** [comment]
Follow the steps in the `ort` docs.
https://github.com/pykeio/ort#how-to-get-binaries

I'd suggest using `load-dynamic`.

**Comment by Fcucgvhhhvjv** [comment]
i checked that instruction but i dont know how to load dynamics . can doing this work?  cargo build ORT_DYLIB_PATH=./libonnxruntime.so after moving libonnxruntime.so to the directory ?

**Comment by decahedron1** [comment]
`ORT_DYLIB_PATH=../../libonnxruntime.so cargo build --features ort-load-dynamic`

**Comment by Fcucgvhhhvjv** [comment]
![Screenshot_2023-08-07-19-58-47-757_com termux](https://github.com/pykeio/diffusers/assets/130964548/13180e02-87b2-4cec-aa83-e5b20554d5dc)


can u check what went wrong?
 i tried with both ORT_DYLIB_PATH=../../libonnxruntime.so cargo build --features ort-load-dynamic and
ORT_DYLIB_PATH=./libonnxruntime.so cargo build --features ort-load-dynamic

**Comment by decahedron1** [comment]
My bad. Try
`ORT_DYLIB_PATH=./libonnxruntime.so cargo build --no-default-features --features ort-load-dynamic,common-schedulers,stable-diffusion`

**Comment by Fcucgvhhhvjv** [comment]
![Screenshot_2023-08-07-20-11-48-582_com termux](https://github.com/pykeio/diffusers/assets/130964548/7d87fb09-e047-4a77-a418-a17521d1d15c)

**Comment by Fcucgvhhhvjv** [comment]
maybe i am missing something ?
im checking this in termux and termux proot environment same result . termux proot environment is running nightly
