### ISSUE TITLE
Does not build: unresolved imports `ort::tensor::FromArray`, `ort::tensor::InputTensor`

### ISSUE THREAD

**Issue by martinellison** [pykeio/diffusers#32]
Example from examples documentation fails with compile errors such as 

- unresolved imports `ort::tensor::FromArray`, `ort::tensor::InputTensor`
-  variant or associated item not found in `ExecutionProvider` (`ExecutionProvider::cuda()`, also `ExecutionProvider::cpu()`)

etc

**Comment by abhemanyus** [comment]
Were you able to solve this?
