### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by geocine** [pykeio/diffusers#5]
Ran the command from documentation

To convert a float16 model from HF (recommended for GPU inference): 
```sh
python3 scripts/hf2pyke.py --fp16 runwayml/stable-diffusion-v1-5@fp16 ~/pyke-diffusers-sd15-fp16/
```

**Comment by sudo-carson** [comment]
This means PyTorch wasn't installed with CUDA. Does your machine have a CUDA GPU? Can you try reinstalling torch using [this setup guide](https://pytorch.org/get-started/locally/)?

**Comment by geocine** [comment]
Thanks this is working
