### ISSUE TITLE
low ram for model conversion

### ISSUE THREAD

**Issue by ClashSAN** [pykeio/diffusers#7]
File "/home/CS/Documents/test/rust/venv/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 627, in load_checkpoint_in_model
    raise ValueError(
    ValueError: At least one of the model submodule will be offloaded to disk, please pass along an `offload_folder`.

**Comment by sudo-carson** [comment]
How much RAM/VRAM is available?

**Comment by ClashSAN** [comment]
Its only 8gb of regular ram, i guess it was not setup for that low. the accelerate module is causing this i think

**Comment by sudo-carson** [comment]
I believe it would be even worse without `accelerate`! 😅

Yeah, I definitely wouldn't recommend CPU inference with only 8 GB of RAM. As per my comment on #9 you'd need around 6 GB of *free* memory to run the float16 models, and I think the float32 models would need closer to 9 GB.

I don't think it's possible to fit Stable Diffusion in such a small space. Maybe 8-bit quantization could work, but I haven't seen anyone do that yet and the results may be terrible with such low precision.

Maybe try giving float16 a shot if you haven't already:
```
python3 scripts/hf2pyke.py --fp16 runwayml/stable-diffusion-v1-5@fp16 ~/pyke-diffusers-sd15-fp16/
```

**Comment by sudo-carson** [comment]
8-bit PTQ seems possible, but with significant quality loss:

![image](https://user-images.githubusercontent.com/61946759/210016876-8aa4477b-a71c-4f05-8e58-2ba73b361ee9.png)

If you're ok with the quality hit, I can try to implement PTQ into hf2pyke which should reduce the RAM required to <4 GB.

**Comment by ClashSAN** [comment]
@sudo-carson 
if you figure it out, could you post a script for quantizing the onnx to int8 properly? I didn't really look into much of the model optimizations onnx can do.
Using [this](https://github.com/LowinLi/stable-diffusion-streamlit/blob/main/src/stable-diffusion-streamlit/pages/model/quantization.py), at 256x256, it is using 1.3gb peak, so I make it generate passively (2-3min) on my old 3 or 4gb ram android phones.

https://github.com/fengwang/Stable-Diffusion-NCNN/issues/1
"It seems to work.
But the model is dynamic quantization, that is, only the weights are quantized to int8, and the input and output of the middle layer of the model is still fp32.
I'll try it later to see how much faster the computation can be and if the output is flawed."

Therefore, I assume the script can be improved.

> I think the float32 models would need closer to 9 GB.

I have the same observation, I used OnnxDiffusersUI and fp32 is ~9gb for 512x512
I also failed to see ram usage drop with fp16 for 512x512 (though I did use a colab, i did read your statement on the model being hardware dependent, I didn't have enough vram[4gb] to convert to onnx with --fp16 )

here below is some visuals with the current int8 script I had used:

<details><summary>Example: (Click to expand:)</summary>

#### 256x256
![000057-00](https://user-images.githubusercontent.com/98228077/210030632-ca581a9a-26a7-47ae-9b22-50aa3b2e9a3b.png)![000047-00](https://user-images.githubusercontent.com/98228077/210030546-82d21679-1191-4b68-ac62-2c15af9386da.png)

#### 384x384
![000051-00](https://user-images.githubusercontent.com/98228077/210030548-2be65309-7b70-4223-9a05-c7c57e4c136e.png)
![000053-00](https://user-images.githubusercontent.com/98228077/210030631-2559928e-a8ae-405d-85a9-ca69d23013e5.png)

#### 512x512

![000044-00](https://user-images.githubusercontent.com/98228077/210030926-884213f4-834f-4fdb-be9e-aff2555e1d38.png)
![000045-00](https://user-images.githubusercontent.com/98228077/210030927-22ccd08a-813b-48cb-9f4e-4272f31a3099.png)
![000046-00](https://user-images.githubusercontent.com/98228077/210030928-caac9fef-0afc-49ad-ab9d-4d48b0e86975.png)
![000048-00](https://user-images.githubusercontent.com/98228077/210031013-6c0c21fb-d34e-4934-8c56-29f42f7bd15a.png)
</details>

**Comment by sudo-carson** [comment]
> I also failed to see ram usage drop with fp16 for 512x512 (though I did use a colab, i did read your statement on the model being hardware dependent, I didn't have enough vram[4gb] to convert to onnx with --fp16 )

I believe fp16 is only hardware dependent when running on GPU, I never had the same issues (black output) with fp16 running on CPU.

---

Those int8 outputs look surprisingly decent (and I didn't know any SD models could generate good results below 512x512 😅). The 'tile' effect is probably due to the VAE. Too much precision is lost with the latents being int8 (and I fear the text encoder may have a similar issue).

I think the text encoder and VAE should stay in float32 or float16. Luckily, these models only have to be loaded at the beginning and end of generation, so we could only load them when necessary and unload them immediately after use to save RAM.

Tomorrow I'll make a 'memory optimized' SD pipeline that only loads models when necessary, and I'll work on int8 quantization as well. You said you were wanting to run SD on Android phones, is there a specific CPU you'd like me to try to optimize for? ONNX Runtime has some execution providers for Qualcomm-powered or Huawei Ascend devices, but I'd need to add support for them in [`ort`](https://github.com/pykeio/ort) before I could use them in Rust.

**Comment by sudo-carson** [comment]
I tested int8 UNet with the [memory-efficient pipeline](https://github.com/pykeio/diffusers/commit/8caa7c73edd27dc1ad2cec48ac4c41dea9ff036c) and the memory usage generating 512x512 did not peak past ~3.2 GB. With 256x256, it did not go above 1.3 GB.

Keeping the VAE in float16 fixes the tiling issue:

![result](https://user-images.githubusercontent.com/61946759/210152870-4324f92f-3f2a-46d5-b33b-1422ebd42416.png)

I converted the UNet with this script:
```py
from onnxruntime.quantization import quantize_dynamic, QuantType

quantize_dynamic(
    model_input='./model-fp32/unet.onnx',
    model_output='./model-int8/unet.onnx',
    per_channel=True,
    reduce_range=True,
    weight_type=QuantType.QUInt8
)
```

I'll add this functionality to `hf2pyke` soon.

**Comment by ClashSAN** [comment]
@sudo-carson 

>memory usage generating 512x512 peaked at ~3.2 GB

the regular inference script I'm using uses 4.7gb at 512x512, so that's nice! thank you, I'll check this out.

>Keeping the VAE in float16 fixes the tiling issue

Yes, good call! I'm having issues with (mostly) unconditional generations, for instance:

    prompt ""
    neg_prompt "bad_prompt"
    scheduler: dpms 
    6-8 steps 
    size (512x512)
    fp16

<details><summary>Example: (Click to expand:)</summary>

![fp16](https://user-images.githubusercontent.com/98228077/210183695-a51ab8e3-c33b-4c79-8597-44f20918bce4.png)


unet Int8, other parts fp16
![3](https://user-images.githubusercontent.com/98228077/210183777-270c0dfe-dfbb-4679-ad87-b04934b92f61.png)
![3unet8](https://user-images.githubusercontent.com/98228077/210183778-22951b6f-da8f-4d3c-aaa1-be49865ef581.png)
![3unetint8_2](https://user-images.githubusercontent.com/98228077/210183779-8b6f52d4-1af6-481d-9261-26e30a311d38.png)

</details>

<details><summary>Seed Based:</summary>

![000008-00](https://user-images.githubusercontent.com/98228077/210183850-bcd9bde0-6d10-48b6-9034-657d1e16d152.png)
![000009-00](https://user-images.githubusercontent.com/98228077/210183852-a1e0be52-eab6-4692-80d1-c0faa0228044.png)
</details>

<details><summary>Regular prompts aesthetic:</summary>

![3fp32vaeandtxtencoder](https://user-images.githubusercontent.com/98228077/210184127-8c2fe548-dfed-4897-b635-1df8af06de86.png)
![3](https://user-images.githubusercontent.com/98228077/210184126-8f44d882-7abf-4c0e-a709-fae5b50e3c13.png)

</details>

>is there a specific CPU you'd like me to try to optimize for? ONNX Runtime has some execution providers for Qualcomm-powered or Huawei Ascend devices

I don't know.

**Comment by ClashSAN** [comment]
I tried the example for low memory:

```
cargo run --example stable-diffusion-memory-efficient -- ./pyke-diffusers-anything-quantized/
   Compiling pyke-diffusers v0.1.0 (/home/CS/Documents/test/rust/diffusers)
    Finished dev [unoptimized + debuginfo] target(s) in 5.45s
     Running `/home/CS/Documents/test/rust/diffusers/target/debug/examples/stable-diffusion-memory-efficient ./pyke-diffusers-anything-quantized/`

```

So I think the unconditional prompt stays a bit broken at int8 , you can see the noise pattern is similar:

<details><summary>Example Script:</summary>

![noise1](https://user-images.githubusercontent.com/98228077/210187941-677d0d7f-f809-4794-9d26-b2635a3e145e.png)
![noise2](https://user-images.githubusercontent.com/98228077/210187942-d99cbd6e-78c0-4ba6-9103-c6959737ff8f.png)

I noticed some visual issues with prompts of low word count, due to unconditional generation having greater effect
![result](https://user-images.githubusercontent.com/98228077/210188061-7883af31-cfed-4b0e-a782-c2075cf1662f.png)
![result2](https://user-images.githubusercontent.com/98228077/210188162-441b2791-ceee-4519-a3b3-a17a07190846.png)

but that can be fixed with higher cfg i guess

</details>

Thanks for this, you rock
